language: php

sudo: false

dist: trusty

notifications:
  email:
    on_success: never
    on_failure: never

branches:
  only:
    - master
    - develop

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - nightly

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=nightly WP_MULTISITE=0

matrix:
  include:
    - php: 7.3
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1
  allow_failures:
      - php: nightly
