language: php

notifications:
  email:
    on_success: never
    on_failure: never

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - nightly

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=nightly WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=nightly WP_MULTISITE=1

allow_failures:
  - php: nightly
